
	
	</div><!-- /content -->
	
	
	<div id="footer">
		<p>
			Copyright &copy; 2007 O’Reilly School of Technology. All rights reserved.<br />
			<span class="subtext">
				Use of this site is subject to express terms of use, which prohibit commercial use of this site.<br />
			</span>        
		</p>
	</div><!-- /footer -->

</div><!-- /page -->

</body>
</html>

<?

echo "<br><br><br>";
echo "<pre>";
print_r($profile_array);
echo "</pre>";

echo "<br><br><br>";
echo "<pre>";
print_r($_POST);
echo "</pre>";

echo "<br><br><br>";
echo "<pre>";
print_r($_GET);
echo "</pre>";

echo "<br><br><br>";
echo "<pre>";
print_r($_SESSION);
echo "</pre>";


?>
